### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by angelagilhotra** [kernel-community/signature-economies#84]
- [x] Deploy contracts on chain
- [x] Update [constants/addresses.js](https://github.com/kernel-community/signature-economies/blob/main/packages/dapp/src/utils/constants/addresses.js) with the contract addresses
- [x] Update [constants/abi.js](https://github.com/kernel-community/signature-economies/blob/main/packages/dapp/src/utils/constants/abi.js) with the latest abi (if it changes, but nice to update just in case)
- [x] Update arweave gateway [here](https://github.com/kernel-community/signature-economies/blob/main/packages/dapp/src/utils/constants/arweave.js)
- [x] Add infura id & arweave key in secrets.json
    - [x] Either create a new random wallet using [tasks/wallet.js](https://github.com/kernel-community/signature-economies/blob/more-fixes/packages/dapp/src/utils/tasks/wallet.js) (`$ node src/utils/tasks/wallet.js`) or add file named `secrets.json` inside `dapp/src/utils` with the following format:
    ```json
        {
           "arweave": {
                "key": {},
                "address": ""
            },
           "infura": {
                 "id":""
            }
        }
    ```
